### ISSUE TITLE
File Structure?

### ISSUE THREAD

**Issue by Otherwa** [Aaditya18SP/FYbscit_html_project#1]
# File Structure Issue

## Problem

The current file structure of the repository is unclear and makes it difficult to navigate and find the necessary files.

## Solution

A clear and organized file structure should be established to improve the usability of the repository. This can include:

- Creating a separate directory for source code files and another for documentation
- Placing related files within the same directory
- Adding a `README.md` file to each directory to provide context and usage instructions for the files within it

## Steps to Reproduce

1. Clone the repository to your local machine
2. Observe the current file structure and note any confusion or difficulties finding necessary files

## Expected Outcome

A well-organized and clear file structure that improves the usability of the repository and makes it easier to navigate and find necessary files.

## Additional Information

Please let us know if you need any additional information or clarification to address this issue.

**Comment by Aaditya18SP** [comment]
ok thanks ...did it for the first time and didn't know it at the time. I have implemented a file structure in the later projects

**Comment by Otherwa** [comment]
Understandable
